//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDuong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public int LectureTypeID { get; set; }
        public int FeatureID { get; set; }
        public string Description_ { get; set; }
    
        public virtual FEATURE FEATURE { get; set; }
        public virtual LECTURERTYPE LECTURERTYPE { get; set; }
    }
}
